apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculatrice-deployment
spec:
  selector:
    matchLabels:
      app: calculatrice
  replicas: 2
  template:
    metadata:
      labels:
        app: calculatrice
    spec:
      containers:
        - name: calculatrice
          image: baretsky24/calculatrice-java-devops:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: calculatrice-svc
spec:
  selector:
    app: calculatrice
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer
